title: MIR Conference Deadlines # (Maintained by @alexanderlerch)
# email: alexander.lerch@gatech.edu
description: Countdowns to top Music Information Retrieval/ Music AI/ Music Signal Processing conference deadlines
author: Abhishek Das

domain: "mir-conferences.audiocontentanalysis.org"
baseurl: ""

twitter_username: alexander lerch
#twitter_hashtag: machinelearning
github_username: alexanderlerch
github_repo: conference-deadlines

markdown: kramdown
#ga_id: UA-36274081-2

include: ['_pages']
